version: '2'

services:
  app:
    volumes:
      - .:/app
      - gems:/home/docker/.rvm/gems
      # Disable the rest of these volumes if the container can safely write to
      # your host filesystem mount named above. You might want to use the rest
      # of these unless you're using dinghy on OSX (usually needed for linux).
      - coverage:/app/coverage
      - bundle-config:/app/spec/gemfiles/.bundle

volumes:
  coverage: {}
  bundle-config: {}
  gems: {}
